version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - run:
          command: dir
      - run:
          command: pwd
      - run:
          command: dotnet.exe publish -c Release -r win10-x86